version: "3"
services:
  frontend:
    container_name: frontend
    #stdin_open: true 
    build: 
      context: ./frontend
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '80:80'
    environment:  
      - BACKEND_URL=http://68.183.155.239:3000/api

  backend:
    container_name: backend 
    build:
        context: ./backend
    depends_on:
      - db  
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    environment:  
      - MONGO_URI=mongodb://db:27017/qube
      - APP_PORT=3000
    ports: ['3000:3000'] 

  db:
    container_name: db
    image: mongo:4.0
    restart: always
