version: "3"
services:
  frontend: 
    image: frontend
    restart: unless-stopped
    ports: 
      - "80:80"
      - "433:433"
    networks:
      - qube-app
  backend:
    image: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - qube-app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
    restart: always
    
networks:
  qube-app:
    driver: bridge
volumes:
  