version: "3"
services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:  
      - BACKEND_URL=http://localhost/qube

  backend:
    container_name: backend 
    build:
        context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db  
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    environment:  
      - MONGO_URL=mongodb://db:27017/qube
      - APP_PORT=80
    ports: ['80:80'] 
    restart: always

  db:
    container_name: db
    image: mongo:4.0
    restart: always
    volumes:
      - db-volume:/data/db

volumes:
  db-volume:
    driver: local