# Production Build

## Stage 1: Build react app
FROM node:12.19-alpine3.9 as frontend

WORKDIR /usr/app/frontend

COPY frontend/package*.json ./

RUN yarn

COPY frontend/ ./
RUN ls

RUN yarn build

## Stage 2: Build server 
FROM node:12.19-alpine3.9

WORKDIR /usr/src/app

COPY --from=frontend /usr/app/frontend/build ./frontend/build
RUN ls

WORKDIR /usr/app/src/server
COPY backend/package*.json ./
RUN npm install
COPY backend/ ./

ENV PORT 8080
EXPOSE 8080

RUN npm start