version: "3"
services:
  frontend: 
    image: frontend
    restart: unless-stopped
    ports: 
      - "80:80"
      - "433:433"
    networks:
      - qube-app
  backend:
    image: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - qube-app
networks:
  qube-app:
    driver: bridge
volumes:
  