version: "3"
services:
  qube-app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"
    env_file: ./backend/.env
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/qube
    depends_on:
      - mongo
    networks:
      - qube-app


  mongo:
    image: mongo:4.0
    restart: always
    volumes:
      - db-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - qube-app
    
networks:
  qube-app:
    driver: bridge

volumes:
  db-volume:
    driver: local
